print("Write how many cups of coffee you will need:")
cups = int(input())
print("For 125 cups of coffee you will need:")
print(str(200 * cups) + " ml of water")
print(str(50 * cups) + " ml of milk")
print(str(15 * cups) + " ml of coffee beans")